name: build
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Download jade
        run: |
          wget https://github.com/JaRoLoz/jade/releases/latest/download/jade_linux_x86_64.zip
          unzip -j ./jade_linux_x86_64.zip

      - name: Build with jade
        run: ./jade . --env github

      - name: Build SQL script
        run: |
          cd sql
          bun i
          bun .
          mv ./full-schema.sql ../Byte.sql

      - name: Cleanup
        run: |
          bun run clean-setup
          bun run clean-build
          rm -f jade_linux_x86_64.zip
          rm -f jade
          rm -rf node_modules

      - name: Publish types to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Package assets
        run: zip -r Byte.zip *

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release
        id: upload-release 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Byte.zip
          asset_name: Byte.zip
          asset_content_type: application/zip